### ISSUE TITLE
W.Tooltip needs to be on top of everything

### ISSUE THREAD

**Issue by gabriela-sartori** [uncover-co/elm-widgets#32]
<img width="190" alt="image" src="https://github.com/uncover-co/elm-widgets/assets/6143964/3490a84f-8ca6-4cd9-b9ed-de31b0fcec86">

**Comment by georgesboris** [comment]
It is not possible for us to statelessly guarantee a floating element will appear on top of everything due to how CSS works - z-index by itself can't escape the context of the parent element.

However:

- For cases such as this one (`W.Table`) we _should_ be able to guarantee that the z-index works. I'm not 100% sure but PR as welcome!

- For cases where z-index won't work we should he able to control the position of the tooltip to mitigate the issue.

- We could also expose some way for the user to define things like z-indexes globally through css-variables so all of our widgets follows a customizable set of z-indexes.

**Comment by georgesboris** [comment]
Tooltips default z-index is now increased on [2.20.0](https://github.com/uncover-co/elm-widgets/releases/tag/2.20.0)
